/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReservaRouteImport } from './routes/reserva'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as IndicacaoRouteImport } from './routes/indicacao'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as FamiliaRouteImport } from './routes/familia'
import { Route as DividasRouteImport } from './routes/dividas'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as ApiFamiliaConvidarRouteImport } from './routes/api/familia/convidar'
import { Route as ApiEmailsSendRouteImport } from './routes/api/emails/send'
import { Route as ApiPublicKiwifyWebhookRouteImport } from './routes/api/public/kiwify/webhook'
import { Route as ApiPublicEmailsCronRouteImport } from './routes/api/public/emails/cron'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaRoute = ReservaRouteImport.update({
  id: '/reserva',
  path: '/reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacaoRoute = IndicacaoRouteImport.update({
  id: '/indicacao',
  path: '/indicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaRoute = FamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => rootRouteImport,
} as any)
const DividasRoute = DividasRouteImport.update({
  id: '/dividas',
  path: '/dividas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/admin/emails',
  path: '/admin/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFamiliaConvidarRoute = ApiFamiliaConvidarRouteImport.update({
  id: '/api/familia/convidar',
  path: '/api/familia/convidar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailsSendRoute = ApiEmailsSendRouteImport.update({
  id: '/api/emails/send',
  path: '/api/emails/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKiwifyWebhookRoute = ApiPublicKiwifyWebhookRouteImport.update({
  id: '/api/public/kiwify/webhook',
  path: '/api/public/kiwify/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailsCronRoute = ApiPublicEmailsCronRouteImport.update({
  id: '/api/public/emails/cron',
  path: '/api/public/emails/cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/contas': typeof ContasRoute
  '/dividas': typeof DividasRoute
  '/familia': typeof FamiliaRoute
  '/importar': typeof ImportarRoute
  '/indicacao': typeof IndicacaoRoute
  '/inicio': typeof InicioRoute
  '/metodo': typeof MetodoRoute
  '/onboarding': typeof OnboardingRoute
  '/orcamento': typeof OrcamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reserva': typeof ReservaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/api/emails/send': typeof ApiEmailsSendRoute
  '/api/familia/convidar': typeof ApiFamiliaConvidarRoute
  '/api/public/emails/cron': typeof ApiPublicEmailsCronRoute
  '/api/public/kiwify/webhook': typeof ApiPublicKiwifyWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/contas': typeof ContasRoute
  '/dividas': typeof DividasRoute
  '/familia': typeof FamiliaRoute
  '/importar': typeof ImportarRoute
  '/indicacao': typeof IndicacaoRoute
  '/inicio': typeof InicioRoute
  '/metodo': typeof MetodoRoute
  '/onboarding': typeof OnboardingRoute
  '/orcamento': typeof OrcamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reserva': typeof ReservaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/api/emails/send': typeof ApiEmailsSendRoute
  '/api/familia/convidar': typeof ApiFamiliaConvidarRoute
  '/api/public/emails/cron': typeof ApiPublicEmailsCronRoute
  '/api/public/kiwify/webhook': typeof ApiPublicKiwifyWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/contas': typeof ContasRoute
  '/dividas': typeof DividasRoute
  '/familia': typeof FamiliaRoute
  '/importar': typeof ImportarRoute
  '/indicacao': typeof IndicacaoRoute
  '/inicio': typeof InicioRoute
  '/metodo': typeof MetodoRoute
  '/onboarding': typeof OnboardingRoute
  '/orcamento': typeof OrcamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reserva': typeof ReservaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/api/emails/send': typeof ApiEmailsSendRoute
  '/api/familia/convidar': typeof ApiFamiliaConvidarRoute
  '/api/public/emails/cron': typeof ApiPublicEmailsCronRoute
  '/api/public/kiwify/webhook': typeof ApiPublicKiwifyWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/assinatura'
    | '/auth'
    | '/contas'
    | '/dividas'
    | '/familia'
    | '/importar'
    | '/indicacao'
    | '/inicio'
    | '/metodo'
    | '/onboarding'
    | '/orcamento'
    | '/privacidade'
    | '/reserva'
    | '/reset-password'
    | '/termos'
    | '/admin/emails'
    | '/convite/$token'
    | '/api/emails/send'
    | '/api/familia/convidar'
    | '/api/public/emails/cron'
    | '/api/public/kiwify/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/assinatura'
    | '/auth'
    | '/contas'
    | '/dividas'
    | '/familia'
    | '/importar'
    | '/indicacao'
    | '/inicio'
    | '/metodo'
    | '/onboarding'
    | '/orcamento'
    | '/privacidade'
    | '/reserva'
    | '/reset-password'
    | '/termos'
    | '/admin/emails'
    | '/convite/$token'
    | '/api/emails/send'
    | '/api/familia/convidar'
    | '/api/public/emails/cron'
    | '/api/public/kiwify/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/assinatura'
    | '/auth'
    | '/contas'
    | '/dividas'
    | '/familia'
    | '/importar'
    | '/indicacao'
    | '/inicio'
    | '/metodo'
    | '/onboarding'
    | '/orcamento'
    | '/privacidade'
    | '/reserva'
    | '/reset-password'
    | '/termos'
    | '/admin/emails'
    | '/convite/$token'
    | '/api/emails/send'
    | '/api/familia/convidar'
    | '/api/public/emails/cron'
    | '/api/public/kiwify/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AssinaturaRoute: typeof AssinaturaRoute
  AuthRoute: typeof AuthRoute
  ContasRoute: typeof ContasRoute
  DividasRoute: typeof DividasRoute
  FamiliaRoute: typeof FamiliaRoute
  ImportarRoute: typeof ImportarRoute
  IndicacaoRoute: typeof IndicacaoRoute
  InicioRoute: typeof InicioRoute
  MetodoRoute: typeof MetodoRoute
  OnboardingRoute: typeof OnboardingRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReservaRoute: typeof ReservaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  ApiEmailsSendRoute: typeof ApiEmailsSendRoute
  ApiFamiliaConvidarRoute: typeof ApiFamiliaConvidarRoute
  ApiPublicEmailsCronRoute: typeof ApiPublicEmailsCronRoute
  ApiPublicKiwifyWebhookRoute: typeof ApiPublicKiwifyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva': {
      id: '/reserva'
      path: '/reserva'
      fullPath: '/reserva'
      preLoaderRoute: typeof ReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacao': {
      id: '/indicacao'
      path: '/indicacao'
      fullPath: '/indicacao'
      preLoaderRoute: typeof IndicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia': {
      id: '/familia'
      path: '/familia'
      fullPath: '/familia'
      preLoaderRoute: typeof FamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividas': {
      id: '/dividas'
      path: '/dividas'
      fullPath: '/dividas'
      preLoaderRoute: typeof DividasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/familia/convidar': {
      id: '/api/familia/convidar'
      path: '/api/familia/convidar'
      fullPath: '/api/familia/convidar'
      preLoaderRoute: typeof ApiFamiliaConvidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/emails/send': {
      id: '/api/emails/send'
      path: '/api/emails/send'
      fullPath: '/api/emails/send'
      preLoaderRoute: typeof ApiEmailsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiwify/webhook': {
      id: '/api/public/kiwify/webhook'
      path: '/api/public/kiwify/webhook'
      fullPath: '/api/public/kiwify/webhook'
      preLoaderRoute: typeof ApiPublicKiwifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/emails/cron': {
      id: '/api/public/emails/cron'
      path: '/api/public/emails/cron'
      fullPath: '/api/public/emails/cron'
      preLoaderRoute: typeof ApiPublicEmailsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AssinaturaRoute: AssinaturaRoute,
  AuthRoute: AuthRoute,
  ContasRoute: ContasRoute,
  DividasRoute: DividasRoute,
  FamiliaRoute: FamiliaRoute,
  ImportarRoute: ImportarRoute,
  IndicacaoRoute: IndicacaoRoute,
  InicioRoute: InicioRoute,
  MetodoRoute: MetodoRoute,
  OnboardingRoute: OnboardingRoute,
  OrcamentoRoute: OrcamentoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ReservaRoute: ReservaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  ApiEmailsSendRoute: ApiEmailsSendRoute,
  ApiFamiliaConvidarRoute: ApiFamiliaConvidarRoute,
  ApiPublicEmailsCronRoute: ApiPublicEmailsCronRoute,
  ApiPublicKiwifyWebhookRoute: ApiPublicKiwifyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
