/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReservaRouteImport } from './routes/reserva'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as IndicacaoRouteImport } from './routes/indicacao'
import { Route as DividasRouteImport } from './routes/dividas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as IndexRouteImport } from './routes/index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaRoute = ReservaRouteImport.update({
  id: '/reserva',
  path: '/reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacaoRoute = IndicacaoRouteImport.update({
  id: '/indicacao',
  path: '/indicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const DividasRoute = DividasRouteImport.update({
  id: '/dividas',
  path: '/dividas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/dividas': typeof DividasRoute
  '/indicacao': typeof IndicacaoRoute
  '/inicio': typeof InicioRoute
  '/metodo': typeof MetodoRoute
  '/onboarding': typeof OnboardingRoute
  '/orcamento': typeof OrcamentoRoute
  '/reserva': typeof ReservaRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/dividas': typeof DividasRoute
  '/indicacao': typeof IndicacaoRoute
  '/inicio': typeof InicioRoute
  '/metodo': typeof MetodoRoute
  '/onboarding': typeof OnboardingRoute
  '/orcamento': typeof OrcamentoRoute
  '/reserva': typeof ReservaRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/auth': typeof AuthRoute
  '/dividas': typeof DividasRoute
  '/indicacao': typeof IndicacaoRoute
  '/inicio': typeof InicioRoute
  '/metodo': typeof MetodoRoute
  '/onboarding': typeof OnboardingRoute
  '/orcamento': typeof OrcamentoRoute
  '/reserva': typeof ReservaRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinatura'
    | '/auth'
    | '/dividas'
    | '/indicacao'
    | '/inicio'
    | '/metodo'
    | '/onboarding'
    | '/orcamento'
    | '/reserva'
    | '/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinatura'
    | '/auth'
    | '/dividas'
    | '/indicacao'
    | '/inicio'
    | '/metodo'
    | '/onboarding'
    | '/orcamento'
    | '/reserva'
    | '/reset-password'
  id:
    | '__root__'
    | '/'
    | '/assinatura'
    | '/auth'
    | '/dividas'
    | '/indicacao'
    | '/inicio'
    | '/metodo'
    | '/onboarding'
    | '/orcamento'
    | '/reserva'
    | '/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssinaturaRoute: typeof AssinaturaRoute
  AuthRoute: typeof AuthRoute
  DividasRoute: typeof DividasRoute
  IndicacaoRoute: typeof IndicacaoRoute
  InicioRoute: typeof InicioRoute
  MetodoRoute: typeof MetodoRoute
  OnboardingRoute: typeof OnboardingRoute
  OrcamentoRoute: typeof OrcamentoRoute
  ReservaRoute: typeof ReservaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva': {
      id: '/reserva'
      path: '/reserva'
      fullPath: '/reserva'
      preLoaderRoute: typeof ReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacao': {
      id: '/indicacao'
      path: '/indicacao'
      fullPath: '/indicacao'
      preLoaderRoute: typeof IndicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividas': {
      id: '/dividas'
      path: '/dividas'
      fullPath: '/dividas'
      preLoaderRoute: typeof DividasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinaturaRoute: AssinaturaRoute,
  AuthRoute: AuthRoute,
  DividasRoute: DividasRoute,
  IndicacaoRoute: IndicacaoRoute,
  InicioRoute: InicioRoute,
  MetodoRoute: MetodoRoute,
  OnboardingRoute: OnboardingRoute,
  OrcamentoRoute: OrcamentoRoute,
  ReservaRoute: ReservaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
